services:
  postgres:
    image: postgres:17
    container_name: cell-clash-db
    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cell_clash

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    build:
      context: .
      dockerfile: ./apps/server/Dockerfile

    container_name: cell-clash-server
    restart: unless-stopped

    ports:
      - "5000:5000"

    depends_on:
      - postgres

    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/cell_clash

  client:
    build:
      context: .
      dockerfile: ./apps/client/Dockerfile

    container_name: cell-clash-client
    restart: unless-stopped

    ports:
      - "3000:3000"

    depends_on:
      - server

    environment:
      server_URL: http://server:5000


volumes:
  postgres_data: